on:
  workflow_call:

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: 'Build'
              run: |
                    DragoSaD-byte/Try_CI_2/sum_param_test@main > sum_param.py
            - name: 'Run'
              run: |
                python sum_param.py 1 2 3