on:
  workflow_call:
    inputs:
      log-file:
        description: 'Path to log file'
        required: false
        default: 'log.bin'
        type: string

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: 'Download artifact'
              uses: actions/download-artifact@v4
              with:
                name: log-file
            - name: 'get_bin'
              run: |
                    echo "import sys
                    if __name__ == '__main__':
                        print(sum(map(int, sys.argv[1:])))" > sum_param.py
            - name: 'Run'
              run: |
                {{ inputs.log-file }} > python sum_param.py